spring:
  application:
    name: cabeleleila

  datasource:
    url: jdbc:mysql://localhost:3306/cabeleleila?createDatabaseIfNotExist=true
    password: root
    username: root

api.security.jwt.secret: "${CABELELEILA_SECRET:12345678}"